---

name: Docker Build and Push


on:
    push:
      branches:
        - main  # Cette action se déclenche sur chaque push vers la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest       

    steps:
      # Étape 1: Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Build de l'image Docker
      - name: Build Docker image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/cowsay:latest .

      # Étape 3: Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 4: Push de l'image Docker vers Docker Hub
      - name: Push Docker image
        run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/cowsay:latest
